spring:
  application:
    name: message-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9191/realms/mghlocal


server:
  port: 8181


logging:
  level:
    root: DEBUG